import Head from 'next/head'
import { DogCard } from '../components/Cards/DogCard/DogCard'
import { Page } from '../components/Page/Page'
import { BreederCard } from '../components/Cards/BreederCard/BreederCard'
import { PageWrapper } from '../components/common/PageWrapper/PageWrapper'

export default function Breeders() {
  return (
    <PageWrapper>
      <Head>
        <title>Taxklubben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page wrap>
        <BreederCard
          breederName="Trollkraft's Kennel"
          contact="Maria Johansson"
          type="Normaltax"
          address="Golvsta 138, 747 91 Alunda"
          phone="0174-10793"
          phone2="070-635 21 05"
          email="gm.johansson1958@gmail.com"
        />
        <BreederCard
          breederName="Kavaröhöjdens kennel"
          contact="Urban Fredlund"
          type="Normaltax"
          address="Skiftesvägen 3, 74334 Storvreta"
          phone="0706757482"
          email="urban.fredlund@kone.com"
        />
        <BreederCard
          breederName="Kennel Jennalee"
          contact="Camilla Asplund"
          type="Dvärgtax"
          address="Hagby 201, 740 20 Vänge"
          phone="0703030213"
          email="kenneljennalee@outlook.com"
          url="https://jennalee.blogg.se"
          instagram="kenneljennalee"
        />
      </Page>
      <footer></footer>
    </PageWrapper>
  )
}
