import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Navbar } from '../components/Navbar/Navbar'
import { NewsCard } from '../components/Cards/NewsCard/NewsCard'
import { Page } from '../components/Page/Page'
import { colors } from '../styles/colors'

const contentful = require('contentful')

const client = contentful.createClient({
  space: process.env.CONTENTFUL_SPACE,
  environment: process.env.CONTENTFUL_ENVIRONMENT,
  accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
})

export default function Home() {
  const [news, setNews] = useState<any[]>([])

  useEffect(() => {
    client
      .getEntries()
      .then((response: any) => setNews(response.items))
      .catch(console.error)
  }, [])

  return (
    <div
      style={{
        backgroundColor: colors.background,
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <Head>
        <title>Taxklubben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Page>
        <>
          {news &&
            news.map((item) => {
              return (
                <NewsCard
                  key={item.fields.header}
                  header={item.fields.header}
                  text={item.fields.text}
                  buttonLabel={item.fields.buttonLabel}
                  onClick={() => null}
                  image={'https:' + item.fields.image.fields.file.url}
                />
              )
            })}
          {news !== null && console.log(news)}
        </>
      </Page>
      <footer></footer>
    </div>
  )
}
