import Head from 'next/head'
import { DogCard } from '../components/DogCard/DogCard'
import { Navbar } from '../components/Navbar/Navbar'
import { NewsCard } from '../components/NewsCard/NewsCard'
import { Page } from '../components/Page/Page'
import { colors } from '../styles/colors'

export default function Home() {
  return (
    <div
      style={{
        backgroundColor: colors.background,
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <Head>
        <title>Taxklubben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Page>
        <NewsCard
          header="Tävling 23 januari"
          text="Nu anordnar vi tävling i finast hund ute i Börje. Anmälan gör du på knappen nedan"
          onClick={() => window.alert('Du är anmäld!')}
          buttonLabel="Anmäl dig här!"
        />
        <NewsCard
          header="Ny webbsida!"
          text="Äntligen är nya webben uppe! Nu kommer den fungera mycket bättre på framförallt små skärmar, men även en stor datorskärm!"
        />
      </Page>
      <footer></footer>
    </div>
  )
}
