import Head from 'next/head'
import { useEffect, useState } from 'react'
import { PrizeCard } from '../components/Cards/PrizeCard/PrizeCard'
import { PageWrapper } from '../components/common/PageWrapper/PageWrapper'
import { Page } from '../components/Page/Page'

const contentful = require('contentful')

const client = contentful.createClient({
  space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE,
  environment: process.env.NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT,
  accessToken: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN,
})

export const Prizes = () => {
  const [prizes, setPrizes] = useState<any[]>([])

  useEffect(() => {
    client
      .getEntries({ content_type: 'prizes' })
      .then((response: any) => setPrizes(response.items))
      .catch(console.error)
  }, [])

  return (
    <PageWrapper>
      <Head>
        <title>Taxklubben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page wrap>
        <>
          {prizes &&
            prizes.map((prize) => {
              return (
                <PrizeCard
                  key={prize.fields.name}
                  title={prize.fields.name}
                  link={prize.fields.file.fields.file.url}
                />
              )
            })}
        </>
      </Page>
    </PageWrapper>
  )
}

export default Prizes
